[package]
name = "tcpping"
version = "0.1.6-beta.6"
edition = "2021"

[dependencies]
ctrlc = "3.2"
tempfile = "3.2"
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde_json = "1.0"
semver = "1.0"