name: Rust Cross Compile and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - aarch64-pc-windows-msvc
          - aarch64-apple-darwin
          - x86_64-apple-darwin
        include:
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            runner: ubuntu-latest
          - target: x86_64-pc-windows-gnu
            runner: windows-latest
          - target: aarch64-pc-windows-msvc
            runner: windows-latest
          - target: aarch64-apple-darwin
            runner: macos-latest
          - target: x86_64-apple-darwin
            runner: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        run: |
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
            export PKG_CONFIG_ALLOW_CROSS=1
            export OPENSSL_DIR=/usr/aarch64-linux-gnu
            export OPENSSL_LIB_DIR=/usr/lib/aarch64-linux-gnu
            export OPENSSL_INCLUDE_DIR=/usr/include/aarch64-linux-gnu
            cargo build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi
        shell: bash

      - name: Package
        shell: bash
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          cd target/${{ matrix.target }}/release
          if [[ "${{ matrix.target }}" == *"-pc-windows-"* ]]; then
            OS="windows"
            if [[ "${{ matrix.target }}" == "x86_64-"* ]]; then
              ARCH="x86_64"
            else
              ARCH="aarch64"
            fi
            EXT="zip"
            7z a ../../../tcpping-${VERSION}-${OS}-${ARCH}.${EXT} tcpping.exe
          elif [[ "${{ matrix.target }}" == *"-apple-darwin" ]]; then
            OS="macos"
            if [[ "${{ matrix.target }}" == "x86_64-"* ]]; then
              ARCH="x86_64"
            else
              ARCH="aarch64"
            fi
            EXT="tar.gz"
            tar czvf ../../../tcpping-${VERSION}-${OS}-${ARCH}.${EXT} tcpping
          else
            OS="linux"
            if [[ "${{ matrix.target }}" == "x86_64-"* ]]; then
              ARCH="x86_64"
            else
              ARCH="aarch64"
            fi
            EXT="tar.gz"
            tar czvf ../../../tcpping-${VERSION}-${OS}-${ARCH}.${EXT} tcpping
          fi
          cd -
          ls -l tcpping-*

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tcpping-${{ matrix.target }}
          path: tcpping-*.*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          gh release create ${GITHUB_REF} -t "tcpping ${VERSION}" --generate-notes
          for asset in tcpping-*/tcpping-*; do
            gh release upload ${GITHUB_REF} "$asset" --clobber
          done
