name: Rust Cross Compile and Release

on:
  push:
    branches:
      - master

jobs:
  check_version_and_release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      should_release: ${{ steps.check_version.outputs.should_release }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get version from Cargo.toml
        id: get_version
        run: |
          VERSION=$(grep '^version =' Cargo.toml | sed 's/.*= *"//' | sed 's/".*//')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Check if tag exists
        id: check_version
        run: |
          if ! git ls-remote --exit-code --tags origin refs/tags/v${{ steps.get_version.outputs.version }} >/dev/null 2>&1; then
            echo "should_release=true" >> $GITHUB_OUTPUT
          else
            echo "should_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tag
        if: steps.check_version.outputs.should_release == 'true'
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git tag -a v${{ steps.get_version.outputs.version }} -m "Release v${{ steps.get_version.outputs.version }}"
          git push origin v${{ steps.get_version.outputs.version }}

  build:
    needs: check_version_and_release
    if: needs.check_version_and_release.outputs.should_release == 'true'
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-pc-windows-gnu
          - aarch64-pc-windows-msvc
          - aarch64-apple-darwin
          - x86_64-apple-darwin
        include:
          - target: x86_64-unknown-linux-gnu
            runner: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            runner: ubuntu-latest
          - target: x86_64-pc-windows-gnu
            runner: windows-latest
          - target: aarch64-pc-windows-msvc
            runner: windows-latest
          - target: aarch64-apple-darwin
            runner: macos-latest
          - target: x86_64-apple-darwin
            runner: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install dependencies
        run: |
          rustup target add ${{ matrix.target }}
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            sudo apt-get update
            sudo apt-get install -y gcc-aarch64-linux-gnu
            sudo apt-get install -y libssl-dev:arm64
          fi
        shell: bash

      - name: Build
        run: |
          if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
            export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
            export PKG_CONFIG_ALLOW_CROSS=1
            export OPENSSL_DIR=/usr/aarch64-linux-gnu
            export OPENSSL_LIB_DIR=/usr/aarch64-linux-gnu/lib
            export OPENSSL_INCLUDE_DIR=/usr/aarch64-linux-gnu/include
            cargo build --release --target ${{ matrix.target }}
          else
            cargo build --release --target ${{ matrix.target }}
          fi
        shell: bash

      - name: Package
        shell: bash
        run: |
          VERSION=${{ needs.check_version_and_release.outputs.version }}
          cd target/${{ matrix.target }}/release
          if [[ "${{ matrix.target }}" == *"-pc-windows-"* ]]; then
            OS="windows"
            if [[ "${{ matrix.target }}" == "x86_64-"* ]]; then
              ARCH="x86_64"
            else
              ARCH="aarch64"
            fi
            EXT="zip"
            7z a ../../../tcpping-v${VERSION}-${OS}-${ARCH}.${EXT} tcpping.exe
          elif [[ "${{ matrix.target }}" == *"-apple-darwin" ]]; then
            OS="macos"
            if [[ "${{ matrix.target }}" == "x86_64-"* ]]; then
              ARCH="x86_64"
            else
              ARCH="aarch64"
            fi
            EXT="tar.gz"
            tar czvf ../../../tcpping-v${VERSION}-${OS}-${ARCH}.${EXT} tcpping
          else
            OS="linux"
            if [[ "${{ matrix.target }}" == "x86_64-"* ]]; then
              ARCH="x86_64"
            else
              ARCH="aarch64"
            fi
            EXT="tar.gz"
            tar czvf ../../../tcpping-v${VERSION}-${OS}-${ARCH}.${EXT} tcpping
          fi
          cd -
          ls -l tcpping-*

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: tcpping-${{ matrix.target }}
          path: tcpping-v*.*

  release:
    needs: [check_version_and_release, build]
    if: needs.check_version_and_release.outputs.should_release == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.check_version_and_release.outputs.version }}
          release_name: tcpping v${{ needs.check_version_and_release.outputs.version }}
          draft: false
          prerelease: ${{ contains(needs.check_version_and_release.outputs.version, '-beta') }}

      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Display structure of downloaded files
        run: ls -R

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for asset in tcpping-*/tcpping-v*; do
            asset_name=$(basename "$asset")
            echo "Uploading $asset_name"
            gh release upload v${{ needs.check_version_and_release.outputs.version }} "$asset" --clobber
          done
